[package]
name = "wacky_bag_fixed"
version = "0.1.0"
edition = "2024"

[dependencies]

cordic = "0.1.5"
wacky_bag = {path="../wacky_bag"}
rand = "0.8.5"
nalgebra = "0.34.0"

[dependencies.fixed]
features = ["num-traits"]
version = "1.29.0"